### ISSUE TITLE
How to solve the memory leak problem when reading data

### ISSUE THREAD

**Issue by 942411526** [RobotiXX/multimodal-fusion-network#1]
Dear author,
Thanks for you great work, I hvae some problem in training. The memory become more and more big in training , I found that the source of this problem may be in
      **" with open(self.pickle_path, 'rb') as data:
            self.content = pickle.load(data)" in the indexer.py**   But I can‘t solve this problem，If you could give me some suggestions, I would be very grateful.

**Comment by bhaba-ranjan** [comment]
Hello @942411526,

I kept all the data **in memory** after reading it once, to speed up the training process. If you keep on reading (I/O operations) on every iteration/epoch, the reading will take a lot of time (Disk reads are slower). 

You can resolve it by 
- Either Increasing the RAM size (IIRC It used around 200GB)
- Or change the script to read on every iteration(The traditional Way) DON'T HOLD it  in memory.

Let me know, if this resolves your problem. We can close the issue, and add it to Know Problems section in the README.md, if the step works.
